//Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: go
  name: go-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: go
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/legal-assistant-chat-persistence-backend: "true"
        io.kompose.service: go
    spec:
      containers:
        - env:
          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                name: legal-assist-secrets-stage
                key: MongoHostStage
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: legal-assist-secrets-stage
                key: MongoPasswordStage
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: legal-assist-secrets-stage
                key: MongoUsernameStage
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: legal-assist-secrets-stage
                key: MongoURIStage
          - name: COOKIE_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: legal-assist-secrets-stage
                key: CookieKeyStage  
          - name: MONGODB_DATABASE
            valueFrom:
              secretKeyRef:
                name: legal-assist-secrets-stage
                key: MongoDBStage                 
          image: {{IMAGENAME}}
          volumeMounts:
          - name: secrets-store01-inline
            mountPath: "/mnt/secrets-store"
            readOnly: true
          name: golang
          ports:
            - containerPort: 4444
              hostPort: 4444
              protocol: TCP
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-system-stage-msi"
      restartPolicy: Always
