apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  secretObjects:
  - secretName: legal-assist-secrets
    type: Opaque
    data:
    - objectName: "MongoHost"
      key: MongoHost
    - objectName: "MongoPassword"
      key: MongoPassword
    - objectName: "MongoUsername"
      key: MongoUsername
    - objectName: "MongoURIProduction"
      key: MongoURIProduction
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: chat-persistence-key
    objects:  |
      array:
        - |
          objectName: MongoHost
          objectType: secret
        - |
          objectName: MongoPassword
          objectType: secret
        - |
          objectName: MongoUsername
          objectType: secret
        - |
          objectName: MongoURIProduction
          objectType: secret
    tenantId: {{TID}}
