apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  secretObjects:
  - secretName: legal-assist-secrets
    type: Opaque
    data:
    - objectName: "MongoHostProduction"
      key: MongoHostProduction
    - objectName: "MongoPasswordProduction"
      key: MongoPasswordProduction
    - objectName: "MongoUsernameProduction"
      key: MongoUsernameProduction
    - objectName: "MongoURIProduction"
      key: MongoURIProduction
    - objectName: "MongoDBProduction"
      key: MongoDBProduction
    - objectName: "CookieKeyProduction"
      key: CookieKeyProduction         
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: chat-persistence-key
    objects:  |
      array:
        - |
          objectName: MongoHostProduction
          objectType: secret
        - |
          objectName: MongoPasswordProduction
          objectType: secret
        - |
          objectName: MongoUsernameProduction
          objectType: secret
        - |
          objectName: MongoURIProduction
          objectType: secret
        - |
          objectName: MongoDBProduction
          objectType: secret
        - |
          objectName: CookieKeyProduction
          objectType: secret          
    tenantId: {{TID}}
