apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
spec:
  provider: azure
  secretObjects:
  - secretName: legal-assist-secrets
    type: Opaque
    data:
    - objectName: "MongoHostStage"
      key: MongoHostStage
    - objectName: "MongoPasswordStage"
      key: MongoPasswordStage
    - objectName: "MongoUsernameStage"
      key: MongoUsernameStage
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: chat-persistence-key
    objects:  |
      array:
        - |
          objectName: MongoHostStage
          objectType: secret
        - |
          objectName: MongoPasswordStage
          objectType: secret
        - |
          objectName: MongoUsernameStage
          objectType: secret
    tenantId: {{TID}}