services:
  go:
    build: .
    container_name: golang
    ports:
      - "4444:4444"
    networks:
      - backend
    # environment:
    #   - MONGODB_URI=${MONGODB_URI}
      
networks:
  backend: