version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  go:
    build: .
    container_name: golang
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      MONGO_USERNAME: mongoadmin
      MONGO_PASSWORD: secret
      MONGO_HOST: mongodb

volumes:
  mongodb_data:
