name: Trigger Azure Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  trigger_pipeline_job:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/ECTM/Legal%20Assist'
          azure-pipeline-name: 'ChatPersistentCI'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}