name: Trigger Pipeline

on:
  pull_request:
    types: [opened, reopened, edited]
    branches:
      - 'main'
  push:
    branches:
      - main

jobs:
  trigger_pipeline_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pipeline
        id: trigger-pipeline
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/ECTM/Legal%20Assist'
          azure-pipeline-name: 'legal_assistant_chat_persistence'
          azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
